### ISSUE TITLE
Growing transactions collection

### ISSUE THREAD

**Issue by sungwoncho** [JackAdams/meteor-transactions#87]
**Versions**

* babrahams:transactions@0.8.2
* Meteor METEOR@1.4.2.3

--------

The `transactions` collection in my app has been constantly growing. Currently,

    db.getCollection('transactions').count({})
    // => 36

It takes up a lot of space. Is this supposed to happen? Can I empty the collection? There is no one using the transaction at the moment.

**Comment by JackAdams** [comment]
Yes, the `transactions` collection on my app is an order of magnitude bigger than any other collection most of the time.  Occasionally, I just blow it all away with a manual `db.transactions.remove({})`, as I don't use it for anything but a temporal undo/redo stack for the last five minutes.

It just grows -- docs are added but never removed.  This is by design but, in practice, not many apps are going to need a record of the entire history of the transactions.

See #15 where the pros and cons of having a method for clearing out old transactions were briefly discussed.

If I was worried about the size of the collections, I'd probably do a `synced-cron` job to clean up anything older than six months every week or so.

**Comment by sungwoncho** [comment]
@JackAdams thanks. I will close this for now.
