### ISSUE TITLE
Specific undo/redo

### ISSUE THREAD

**Issue by gcacars** [JackAdams/meteor-transactions#9]
How  can I undo or redo an specific transaction? Like: tx.undo({'_id':"vfXWyBZvZRCv29tT2"}); ?

**Comment by JackAdams** [comment]
Yes, good question.  This is something that I've been planning but haven't implemented.  The method will probably look more like `tx.undo("vfXWyBZvZRCv29tT2");`.  I'll try to roll this out asap.

**Comment by JackAdams** [comment]
This functionality is now added (at least in the Github repo).  I'll do some testing and then publish a new version of the package on atmosphere later today.

**Comment by JackAdams** [comment]
Okay, that's now published to atmosphere in the latest release.

**Comment by gcacars** [comment]
Wow! Thanks Jack, I do a fork from you: https://github.com/gcacars/meteor-transactions.
Works great, but doesn't work with commits, only with normal tx.insert, tx.remove....
I try the new version from you.
Thanks a lot man!

**Comment by gcacars** [comment]
Yeah! It works great!

**Comment by JackAdams** [comment]
Your code was very similar to mine, in the end. There were a few other subtleties to work out and some security implications to consider.  In fact, because I was looking into the code, I noticed a bug in one of my security checks -- so thank you for prompting me to look into it!  The whole package is better as a result.
